### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by fire** [PeizhuoLi/walk-the-dog#1]
Hi,

As I work with FOSS opensource game engines like Godot Engine is it possible to license this code so it's aligned with https://github.com/godotengine/godot/blob/master/LICENSE.txt?

So this research can benefit more people.

Edited:

Thank you all for your great work!

**Comment by PeizhuoLi** [comment]
Hi, sorry for the late reply. A LICENSE file has been added to the project.
